export const HERO_SLIDE = [
  { id: 1, img: "/images/hero/1.jpg", alt: "slide 1" },
  { id: 2, img: "/images/hero/2.jpg", alt: "slide 2" },
  { id: 3, img: "/images/hero/3.jpg", alt: "slide 3" },
  { id: 4, img: "/images/hero/4.jpg", alt: "slide 4" },
  { id: 5, img: "/images/hero/5.jpg", alt: "slide 5" },
];

export const HERO_RECOMMENDATION = [
  {
    id: 1,
    img: "/images/hero/1.jpg",
    alt: "slide 1",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 2,
    img: "/images/hero/2.jpg",
    alt: "slide 2",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 3,
    img: "/images/hero/3.jpg",
    alt: "slide 3",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 4,
    img: "/images/hero/4.jpg",
    alt: "slide 4",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 5,
    img: "/images/hero/5.jpg",
    alt: "slide 5",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 6,
    img: "/images/hero/1.jpg",
    alt: "slide 6",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 7,
    img: "/images/hero/2.jpg",
    alt: "slide 7",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 8,
    img: "/images/hero/3.jpg",
    alt: "slide 8",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 9,
    img: "/images/hero/1.jpg",
    alt: "slide 1",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 10,
    img: "/images/hero/2.jpg",
    alt: "slide 2",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 11,
    img: "/images/hero/3.jpg",
    alt: "slide 3",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 12,
    img: "/images/hero/4.jpg",
    alt: "slide 4",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 13,
    img: "/images/hero/5.jpg",
    alt: "slide 5",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 14,
    img: "/images/hero/1.jpg",
    alt: "slide 6",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 15,
    img: "/images/hero/2.jpg",
    alt: "slide 7",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
  {
    id: 16,
    img: "/images/hero/3.jpg",
    alt: "slide 8",
    price: 500,
    name: "Hotel California",
    rating: 5,
    reviewsCount: 49,
    cityLocation: "Paris",
    countryLocation: "France",
  },
];

export const EXPLORE_BREAKPOINTS = {
  568: {
    slidesPerView: 2,
    spaceBetween: 8,
  },
  768: {
    slidesPerView: 3,
    spaceBetween: 12,
  },
  1024: {
    slidesPerView: 4,
    spaceBetween: 16,
  },
  1280: {
    slidesPerView: 5,
    spaceBetween: 20,
  },
};

export const EXPLORE_SLIDE = [
  { id: 1, img: "/images/city/bali.jpg", name: "bali" },
  { id: 2, img: "/images/city/bangkok.jpg", name: "bangkok" },
  { id: 3, img: "/images/city/cairo.jpg", name: "cairo" },
  { id: 4, img: "/images/city/jakarta.jpg", name: "jakarta" },
  { id: 5, img: "/images/city/las-vegas.jpg", name: "las vegas" },
  { id: 6, img: "/images/city/london.jpg", name: "london" },
  { id: 7, img: "/images/city/madrid.jpg", name: "madrid" },
  { id: 8, img: "/images/city/moscow.jpg", name: "moscow" },
  { id: 9, img: "/images/city/paris.jpg", name: "paris" },
  { id: 10, img: "/images/city/rome.jpg", name: "rome" },
  { id: 11, img: "/images/city/sydney.jpg", name: "sydney" },
];
